//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string fname { get; set; }
        public string Lname { get; set; }
        public bool Isadmin { get; set; }
        public string ConfirmPassword { get; internal set; }
    }
}
